name: build_installer_windows
on: 
  workflow_dispatch:
  push:
    branches: 
      - master
jobs:
  build_installer_windows:
    runs-on: [self-hosted, windows]
    steps:
      - name: Cleanup working directory
        working-directory: ${{ github.workspace }}
        run: del *.* /Q /S
        shell: cmd
      - name: Checkout HISE repository
        uses: actions/checkout@v1
        with:
          ref: 'master'
      - name: Build HISE Standalone & VST Plugin
        working-directory: ${{ github.workspace }}/tools/auto_build/
        run: 01_BuildHISE.bat
        shell: cmd
      - name: Build Installer
        working-directory: ${{ github.workspace }}/tools/auto_build/
        run: 02_BuildInstaller.bat
        shell: cmd
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: HISE Installer
          path: ${{ github.workspace }}/tools/auto_build/Output/*.exe
