name: CI build Windows
on: 
  workflow_dispatch:
  push:
    branches: 
      - develop
jobs:
  hise_ci_win:
    runs-on: [self-hosted, windows]
    steps:
      - name: Cleanup working directory
        working-directory: ${{ github.workspace }}
        run: del *.* /Q /S
        shell: cmd
      - name: Checkout HISE repository
        uses: actions/checkout@v1
        with:
          ref: 'develop'
      - name: Build HISE CI, run unit tests & export demo project
        working-directory: ${{ github.workspace }}/tools/auto_build/
        run: build_ci.bat
        shell: cmd
